### ISSUE TITLE
BBL installation in MSFS 2024

### ISSUE THREAD

**Issue by SOFTWAREKOCH** [RoystonS/BetterBravoLights#80] opened 2024-11-23 18:16 UTC
### Software version

0.8.2

### Flight Simulator installation type

Windows Store

### Problem

Hi Royston,

when installing the BBL i get a error because the path seems to bewrong.
In my Opinion it should be :  C:\Users\xxxxxxx\AppData\Local\Packages\Microsoft.Limitless_8wekyb3d8bbwe\LocalCache\
for the new MSFS 2024.

I was looking for the Version 0.9.0 but i could not find a compiled version.

May be you have already a working version.

Thx in advance.

Dietmar

### Expected behaviour

![Error when using MSFS 2024](https://github.com/user-attachments/assets/df6cbd92-8379-4f6d-8477-e005287d69bd)

**Comment by RoystonS** [comment] 2024-11-23 19:19
Duplicate of #79. Will address in that issue.

**Closed as completed by RoystonS** 2024-11-23 19:19 UTC
Labels: bug, duplicate
